contact/urls.py
from contact import views
from django.urls import path

app_name ='contact'

urlpatterns = [
    
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    
    #CRUD
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create , name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    #USER
    path('user/create/', views.register , name='register'),
    path('user/login/', views.login_views, name='login'),
    path('user/logout/', views.logout_views, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
    #path('<int:contact_id>/update/', views.contact, name='contact'),
    #path('<int:contact_id>/delete/', views.contact, name='contact'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
    
]
# configuração para conseguir abrir a url das pictures
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
import pickle
from pyexpat import model
from tabnanny import verbose
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#class criada para category
class Category(models.Model):
    
    #class criada para corrigir erro ortografico
    class Meta:
        verbose_name = 'Category'

    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return f'{self.name}'

#blank=True, ex: last_name = models.CharField(max_length=50, blank=True), com blank não é obrigatorio colocar o last name
class Contact(models.Model):
    firt_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self) -> str:
        return f'{self.firt_name} {self.last_name}'

   

contact/views/forms.py
from cProfile import label
from django.shortcuts import render, redirect, get_object_or_404
from contact.models import Contact
from django import forms
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.contrib.auth import authenticate, login, password_validation
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

class ContactForm(forms.ModelForm):
    phone = forms.CharField(
        validators=[
            RegexValidator(
                regex=r'^\d{11}$',  # Aceita apenas números com exatamente 11 dígitos
                message='O telefone deve conter exatamente 11 dígitos numéricos.'
            )
        ],
        label="Telefone",
        help_text="Digite o número de telefone com 11 dígitos, incluindo o DDD (ex: 11987654321)."
    )
    picture = forms.ImageField(
        label= 'Imagem',
        help_text= 'Escolha uma imagem para adicionar ao contato (opcional).',
        required=False,
        widget=forms.FileInput(attrs={
            'accept' : 'image/*',
        })
        )
    
    class Meta:
        model = Contact
        fields = ('firt_name', 'last_name', 'phone',
                  'email','description', 'category', 'picture')
        labels = {
            'firt_name': 'Nome',
            'last_name': 'Sobrenome',
            'phone': 'Telefone',
            'email': 'E-mail',
            'description': 'Descrição',
            'category': 'Categoria',
        }
        
        
    def clean(self):
        cleaned_data = self.cleaned_data
        firt_name = cleaned_data.get('firt_name')
        last_name = cleaned_data.get('last_name')

        if firt_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )
            
            msgl = ValidationError(
                'Segundo nome igual ao Primeiro',
                code='invalid'
            )
            self.add_error('firt_name', msg)
            self.add_error('last_name', msgl)

        return super().clean()
    
    def clean_firt_name(self):
        cleaned_data = self.cleaned_data
        firt_name = cleaned_data.get('firt_name')
        msgf = ValidationError('ABC, não é um nome valido', code='invalid')
        if firt_name == 'ABC':
            self.add_error('firt_name', msgf)
            
        return firt_name

class RegisterForm(UserCreationForm):
    firt_name = forms.CharField(required=True,label='Nome', min_length=3)
    last_name = forms.CharField(required=True,label='Sobrenome' ,min_length=3)
    email = forms.EmailField(label='E-mail')
    
    class Meta:
        model = User
        fields = (
            'firt_name', 'last_name', 'email','username', 'password1', 'password2',
        )
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email', ValidationError('E-mail já cadastrado', code='invalid')
            )
        return email
        
    
    
    
class RegisterUpdateForm(forms.ModelForm):
    firt_name = forms.CharField(
        label="Nome",
        min_length=2,
        max_length=30,
        required=True,
        help_text='Obrigatorio.',
        error_messages={
            'min_length': 'Por favor, adicionar pelo menos 2 letras.'
        }
    )
    
    email = forms.EmailField(
        label='E-mail',
        )
    
    last_name = forms.CharField(
        label="Sobrenome",
        min_length=2,
        max_length=30,
        required=True,
        help_text='Obrigatorio'
    )

    password1 = forms.CharField(
        label="Senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "nova-senha"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Confirme a senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "nova-senha"}),
        help_text='Use a mesma senha de antes.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'firt_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas devem ser iguais')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('E-mail ja registrado', code='invalid')
                )

        return email
    
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        
        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error('password1', ValidationError(errors))
                
        return password1
    
@login_required(login_url='contact:login')   
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)
        messages.success(request, 'Contato criado com Sucesso')
        return render(request, 'contact/create.html', context)
    
    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }
    return render(request, 'contact/create.html', context)

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id,))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save()
            messages.success(request, 'Contato atulizado com sucesso')
            return redirect('contact:update', contact_id=contact.pk)
        return render(request, 'contact/create.html', context)
    
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }
    return render(request, 'contact/create.html', context)


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    confirmacao = request.POST.get('confirmacao', 'nao')

    if confirmacao == 'sim':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmacao': confirmacao,
        }
    )
    

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.models import Contact
from django import forms
from django.core.exceptions import ValidationError
from django.urls import reverse



class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={
            'accept' : 'image/*',
        })
    )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Contact
        fields = ('firt_name', 'last_name', 'phone',
                  'email','description', 'category', 'picture')
        
    

def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)
        return render(request, 'contact/create.html', context)
    
    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }
    return render(request, 'contact/create.html', context)


def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse('contact:update', args=(contact_id,))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact,)
        context = {
            'form': form,
            'form_action': form_action,
        }
        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)
        return render(request, 'contact/create.html', context)
    
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }
    return render(request, 'contact/create.html', context)



def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    confirmacao = request.POST.get('confirmacao', 'nao')

    if confirmacao == 'sim':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmacao': confirmacao,
        }
    )



def clean(self):
        # cleaned_data = self.cleaned_data
    cleaned_data = self.cleaned_data
    first_name = cleaned_data.get('first_name')
    last_name = cleaned_data.get('last_name')
        
    if first_name == last_name:
        msg = ValidationError(
        'Primeiro nome não pode ser igual ao segundo',
        code='invalid')
        self.add_error('first_name', msg)
        self.add_error('last_name', msg)

        return super().clean()

contact/views/contact_views.py
#criado para melhor organização, junto a pasta views
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator



# Create your views here.
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
        }
    
    return render(request, 'contact/index.html', context)

def search(request):
    search_value = request.GET.get('q', '').strip()
    
    if search_value == '':
        return redirect('contact:index')
   
    contacts = Contact.objects.filter(show=True).filter(Q(firt_name__icontains=search_value) | 
                                                        Q(last_name__icontains=search_value) |
                                                        Q(phone__icontains=search_value) |
                                                        Q(email__icontains=search_value)
                                                        )\
                                                            .order_by('id')
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - ',    
        'search_value': search_value,
         
    }
    
    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    
    titulo = f'{single_contact.firt_name} {single_contact.last_name} - '
    
    
    context = {
        'contact': single_contact,
        'site_title': titulo,
    
    }
    return render(request, 'contact/contact.html', context)

contact/views/user_forms.py
from django.contrib import auth, messages
from django.shortcuts import redirect, render
from contact.views import RegisterForm, RegisterUpdateForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required




def register(request):
    form = RegisterForm()
  
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario Registrado')
            return redirect('contact:index')
    return render(request,'contact/register.html',
                  {
                      'form': form,

                  })
    
def login_views(request):
    form = AuthenticationForm(request)
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request,f'Login efetuado com sucesso')
            return redirect('contact:index')
            
        else:
            messages.error(request, 'Nome de usuário ou senha incorretos.')
    
    return render(request,'contact/login.html',{
        'form': form
    })
    
def logout_views(request):
    auth.logout(request)
    messages.success(request, 'Logout feito com sucesso')
    return redirect('contact:login')

@login_required(login_url='contact:login')
def user_update(request):
    if not request.user.is_authenticated:
         return redirect('contact:login')
     
    form =  RegisterUpdateForm(instance=request.user)
        
    if request.method == 'POST':
        form = RegisterUpdateForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario atualizado com sucesso')
            return redirect('contact:index')
         
    return render(request,'contact/update_user.html',
                  {
                      'form': form,

                  })
    
    

contact/templates/contact/contact.html
{% extends 'global/base.html' %}
{% block content %}
  <div class="single-contact">
    <h1 class="single-contacth1">{{ contact.firt_name }} {{ contact.last_name }}</h1>

    <p>
      <b>ID:</b> {{ contact.id }}
    </p>
    <p>
      <b>E-mail:</b> {{ contact.email }}
    </p>
    <p>
      <b>Telefone:</b> {{ contact.phone }}
    </p>
    <p>
      <b>Data de Criação:</b> {{ contact.created_date }}
    </p>
    <p>
      <b>Descrição:</b> {{ contact.description }}
    </p>
    <p>
      <b>Categoria:</b> {{ contact.category.name }}
    </p>
    {% if contact.picture %}
    <p>
        <img src="{{contact.picture.url}}" alt="{{ contact.firt_name}} {{ contact.last_name}}">
    </p>
    {% endif %}
   
    {% if contact.owner  %}
    <div class="display-form">
    <form action="{% url 'contact:update' contact.id %}" method="get" > 
      <div class="div-botao-atualizar">
      <button class="botao-atualizar">
      <strong>Atualizar</strong>
      </button>
      </div>
    </form>

    <form action="{% url 'contact:delete' contact.id %}" method="POST" class="form-botao"> 
      {% csrf_token %}
      <div class="div-botao-deletar">
      {% if confirmacao == 'nao'  %}
      <input type="hidden" name="confirmacao" value="sim">
      <button type="submit" class="botao-deletar">
      <strong>Confirma?</strong> 
      </button>
      </div>
      {% else %}
      <div class="div-botao-deletar">
        <button type="submit" class="botao-deletar">
        <strong>Deletar</strong>
        </div>
      {% endif %}
      </div>
    </form>
    {% endif %}
{% endblock %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
    <h2 class="createh2">Contato</h2>

    <form class="form-create" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-content">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>

            {{ field }}
            {{ field.errors }}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}
          </div>
          {% if field.name == 'picture' and field.value.url %}
            <div>
              <img src="{{ field.value.url }}" alt="" />
            </div>
          {% endif %}
        {% endfor %}

        {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}
      </div>
      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Criar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  {% if page_obj  %}
    <div class="responsive-table">
      <table class="contacts-table">
        <caption class="table-caption">Contatos</caption>

        <thead>
          <tr class="table-row_table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">Nome</th>
            <th class="table-header">Sobrenome</th>
            <th class="table-header">Telefone</th>
            <th class="table-header">E-mail</th>
          </tr>
        </thead>

        <tbody>
          {% for contact in page_obj %}
            <tr class="table-row">
              <td class="table-info">
                <a class="table-link" href="{% url 'contact:contact' contact.id %}">{{ contact.id }}</a>
              </td>
              <td class="table-info">{{ contact.firt_name }}</td>
              <td class="table-info">{{ contact.last_name }}</td>
              <td class="table-info">{{ contact.phone }}</td>
              <td class="table-info">{{ contact.email }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
    <div class="single-contact">
      <h1 class="single-contacth1">
        Nenhum contato encontrado.
      </h1>
  {% endif %}
{% endblock %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  
  <div class="form-wrapper">
    <h2 class="createh2">Entrar</h2>


    <form class="form-login" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      {% for field in form  %}
      <div class="form-content">
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{field.label}}</label>
         
          {{ field }}
          {{ field.errors}}
          
          {% if field.help_text %}
          <p class="help-text">{{field.help_text}}</p>
          {% endif %}
        </div>
      {% endfor %}

    {% if form.non_field_errors %}
  <div class="form-content">
    <div class="form-group">
      <div class="message error">
        {{ form.non_field_errors }}
      </div>
    </div>
  </div>
    {% endif %}
      <div class="form-group-login">
        <button class="btn" type="submit">Entrar</button>
      </div>
  </div>
    </form>
{% endblock %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
  
  <div class="form-wrapper">
    <h2 class="createh2">Registrar</h2>

    <form  class="form-register" action="{{ form_action }}" method="POST" enctype="multipart/form-data">

      {% csrf_token %}

      {% for field in form  %}
      <div class="form-content">
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{field.label}}</label>
         
          {{ field }}
          {{ field.errors}}
          
          {% if field.help_text %}
          <p class="help-text">{{field.help_text}}</p>
          {% endif %}
        </div>
      {% endfor %}
      
      </div>
        <div class="form-group-register">
          <button class="btn" type="submit">Registrar</button>
        </div>
    </form>
  </div>
{% endblock %}

contact/templates/contact/update_user.html
{% extends 'global/base.html' %}

{% block content %}
  
  <div class="form-wrapper">
    <h2 class="createh2">Atualizar contato</h2>

    <form class="form-update" action="{{ form_action }}" method="POST" enctype="multipart/form-data">

      {% csrf_token %}

      {% for field in form  %}
      <div class="form-content">
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{field.label}}</label>
         
          {{ field }}
          {{ field.errors}}
          
          {% if field.help_text %}
          <p class="help-text">{{field.help_text}}</p>
          {% endif %}
        </div>
      {% endfor %}
      
      </div>
        <div class="form-group-register">
          <button class="btn" type="submit">Atualizar</button>
        </div>
    </form>
  </div>
{% endblock %}